### PR TITLE
Update Prisma to Prisma 1

### PR DESCRIPTION
**Pull request by Jolg42**
New default Prisma version is Prisma 2 see https://www.prisma.io/

### CODE REVIEW

**Comment by githubsaturn** [comment]
How different prisma 1 and 2 are? Why do we want to explicitly mention prisma 1 on website. We don't usually mention the versions.

**Comment by Jolg42** [comment]
@githubsaturn I understand your point, here it's completely different :)

https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/how-to-upgrade#main-differences-between-prisma-1-and-prisma-2

Screen Shot 2020-07-02 at 16 35 39

**Comment by githubsaturn** [comment]
I understand, but still this is just a major version upgrade. It's not two different things. Plus this is just an example list and mentioning a version here would cause confusion as to why other apps don't have version.

**Comment by githubsaturn** [comment]
Also, hopefully we'll get to add prisma 2 to the list soon.

**Comment by Jolg42** [comment]
Working at Prisma, I can tell you it's basically 2 different products :)

There is an upgrade path possible between both but the mental model is quite different.

**Comment by githubsaturn** [comment]
Working at prisma is the green pass for this change 👍

**Comment by Jolg42** [comment]
Thanks 👍 💯

**Pull request merged**
