### PR TITLE
Updated Persistent App directory

### PR DESCRIPTION
**Pull request by Fabian9799**
Updated the text for a better understanding since it is currently only explained how to access the folder from within the docker container when a specific path is set

### CODE REVIEW

**Comment by githubsaturn** [comment]
> and can be accessed in your docker container in `/var/usr/YOUR_PATH`.

This is not entirely true. The path depends on how you set up the path in your app configuration. It could be `/anything/here/path` in your container...

**Comment by Fabian9799** [comment]
Doesn't that only apply when you choose the "Set specific host path" option?

**Comment by githubsaturn** [comment]
No. 

The path inside the docker container is always customizable.

**Comment by Fabian9799** [comment]
So i could use `../../../DIRECTORY` as the "Path in app" path to get it into the "app" folder right? since the default is ` /var/usr/store`

**Comment by githubsaturn** [comment]
What do you mean by " the default is `/var/usr/store`"?  Where do you get this from?

**Comment by Fabian9799** [comment]
From here https://caprover.com/docs/persistent-apps.html#docsNav
it says "and the file will be available on your server at /var/usr/myfile.txt"
and "store" is just the path entered for the "Path in app"

**Comment by githubsaturn** [comment]
It's just an **example**:
image

Path in the app is "path in the container".

**Comment by Fabian9799** [comment]
Oh got it. I was confused about the "server" part since i didn't realize that "server" means the docker container / the app in the third line of your screenshot

**Comment by githubsaturn** [comment]
Server is the host machine, not the container. I'll make this a bit more clear tomorrow.

**Pull request closed without merging**
