### PR TITLE
Update service-update-override.md: Adding Secrets to Service Update Override

### PR DESCRIPTION
**Pull request by omars44**
Added an example on how to add secrets to a service

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by githubsaturn** [comment]
On a second look, have you tested this? I looked at the documentation and it looks like secrets are supposed to be a object array. So this single field array that you posted doesn't work.

I revert this PR until you confirm that this is fully tested and it works.

image

**Comment by omars44** [comment]
@githubsaturn it is an array of objects, that has 1 object inside it, you mean to add more objects so it's more clear to understand ? or you mean to add the extra File ?

**Comment by githubsaturn** [comment]
Sorry - I didn't explain well.

Not all fields are present in the addition that you posted. You need something like this:
```
{
                            File: {
                                Name: "somename",
                                UID: '0',
                                GID: '0',
                                Mode: 292
                            },
                            SecretID: "someid",
                            SecretName:  "somename"
}
```


Have you tested omiting the `File` object. and would it work without the file object?

**Comment by omars44** [comment]
@githubsaturn I'll test all scenarios, and update the PR with the outcomes, thanks for raising this issue

**Pull request merged**
