### PR TITLE
ssh keygen command that is compatible with caprover

### PR DESCRIPTION
**Pull request by vinaydate**

### CODE REVIEW

**Comment by vinaydate** [comment]
The reference issue is [this](https://github.com/caprover/caprover/issues/464).

I have personally verified the generated key with suggested command

**Comment by githubsaturn** [comment]
Thanks, Vinay! But I think the problem with the previous command in the doc was the "format", not the key type which I've already fixed here:
https://github.com/caprover/caprover-website/commit/022abbe17e544e9b507760e1e7bbf372f7f1f279


Would you please be able to test the current command in the doc and confirm whether it works or not for you? 
```
ssh-keygen -m PEM -t ed25519 -C "yourname@example.com" -f ./deploykey -q -N ""
```

Github considers the `rsa` keys legacy and obsolete:
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

image

**Comment by vinaydate** [comment]
Hi

Appreciate your quick review.

I had tried

ssh-keygen -m PEM -t ed25519 -C ***@***.***" -f ./deploykey -q -N ""

this command and it did not work in my case. But today, when I thought to give it a try. (Due consideration being, you must have tried and tested this). And it worked. Don't what was missing earlier. Anyways, thanks to your whole team for Caprover.

So, I will close the pull request

________________________________

**Comment by githubsaturn** [comment]
Thanks! Glad to hear that the current command works well. 

Feel free to reopen of things change.

**Comment by yangcheng** [comment]
in my case I have to create a new key without passphrase. in UI I did not find a place to enter passphrase

**Pull request closed without merging**
